/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PartidaRouteImport } from './routes/partida'
import { Route as JogarRouteImport } from './routes/jogar'
import { Route as ComoJogarRouteImport } from './routes/como-jogar'
import { Route as IndexRouteImport } from './routes/index'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidaRoute = PartidaRouteImport.update({
  id: '/partida',
  path: '/partida',
  getParentRoute: () => rootRouteImport,
} as any)
const JogarRoute = JogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoJogarRoute = ComoJogarRouteImport.update({
  id: '/como-jogar',
  path: '/como-jogar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-jogar': typeof ComoJogarRoute
  '/jogar': typeof JogarRoute
  '/partida': typeof PartidaRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-jogar': typeof ComoJogarRoute
  '/jogar': typeof JogarRoute
  '/partida': typeof PartidaRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-jogar': typeof ComoJogarRoute
  '/jogar': typeof JogarRoute
  '/partida': typeof PartidaRoute
  '/perfil': typeof PerfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/como-jogar' | '/jogar' | '/partida' | '/perfil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/como-jogar' | '/jogar' | '/partida' | '/perfil'
  id: '__root__' | '/' | '/como-jogar' | '/jogar' | '/partida' | '/perfil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoJogarRoute: typeof ComoJogarRoute
  JogarRoute: typeof JogarRoute
  PartidaRoute: typeof PartidaRoute
  PerfilRoute: typeof PerfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partida': {
      id: '/partida'
      path: '/partida'
      fullPath: '/partida'
      preLoaderRoute: typeof PartidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogar': {
      id: '/jogar'
      path: '/jogar'
      fullPath: '/jogar'
      preLoaderRoute: typeof JogarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-jogar': {
      id: '/como-jogar'
      path: '/como-jogar'
      fullPath: '/como-jogar'
      preLoaderRoute: typeof ComoJogarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoJogarRoute: ComoJogarRoute,
  JogarRoute: JogarRoute,
  PartidaRoute: PartidaRoute,
  PerfilRoute: PerfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
