/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoJogarRouteImport } from './routes/como-jogar'
import { Route as JogarRouteImport } from './routes/jogar'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as PartidaRouteImport } from './routes/partida'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as SalaCodeRouteImport } from './routes/sala.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoJogarRoute = ComoJogarRouteImport.update({
  id: '/como-jogar',
  path: '/como-jogar',
  getParentRoute: () => rootRouteImport,
} as any)
const JogarRoute = JogarRouteImport.update({
  id: '/jogar',
  path: '/jogar',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidaRoute = PartidaRouteImport.update({
  id: '/partida',
  path: '/partida',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaCodeRoute = SalaCodeRouteImport.update({
  id: '/sala/$code',
  path: '/sala/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-jogar': typeof ComoJogarRoute
  '/jogar': typeof JogarRoute
  '/online': typeof OnlineRoute
  '/partida': typeof PartidaRoute
  '/perfil': typeof PerfilRoute
  '/sala/$code': typeof SalaCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-jogar': typeof ComoJogarRoute
  '/jogar': typeof JogarRoute
  '/online': typeof OnlineRoute
  '/partida': typeof PartidaRoute
  '/perfil': typeof PerfilRoute
  '/sala/$code': typeof SalaCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-jogar': typeof ComoJogarRoute
  '/jogar': typeof JogarRoute
  '/online': typeof OnlineRoute
  '/partida': typeof PartidaRoute
  '/perfil': typeof PerfilRoute
  '/sala/$code': typeof SalaCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-jogar'
    | '/jogar'
    | '/online'
    | '/partida'
    | '/perfil'
    | '/sala/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-jogar'
    | '/jogar'
    | '/online'
    | '/partida'
    | '/perfil'
    | '/sala/$code'
  id:
    | '__root__'
    | '/'
    | '/como-jogar'
    | '/jogar'
    | '/online'
    | '/partida'
    | '/perfil'
    | '/sala/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoJogarRoute: typeof ComoJogarRoute
  JogarRoute: typeof JogarRoute
  OnlineRoute: typeof OnlineRoute
  PartidaRoute: typeof PartidaRoute
  PerfilRoute: typeof PerfilRoute
  SalaCodeRoute: typeof SalaCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-jogar': {
      id: '/como-jogar'
      path: '/como-jogar'
      fullPath: '/como-jogar'
      preLoaderRoute: typeof ComoJogarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogar': {
      id: '/jogar'
      path: '/jogar'
      fullPath: '/jogar'
      preLoaderRoute: typeof JogarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partida': {
      id: '/partida'
      path: '/partida'
      fullPath: '/partida'
      preLoaderRoute: typeof PartidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sala/$code': {
      id: '/sala/$code'
      path: '/sala/$code'
      fullPath: '/sala/$code'
      preLoaderRoute: typeof SalaCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoJogarRoute: ComoJogarRoute,
  JogarRoute: JogarRoute,
  OnlineRoute: OnlineRoute,
  PartidaRoute: PartidaRoute,
  PerfilRoute: PerfilRoute,
  SalaCodeRoute: SalaCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
